# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks

#tasks:
#  - name: Script Task
#    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
#    command: echo 'start script'

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
#image: gitpod/workspace-postgres

image: gitpod/workspace-postgres:2024-01-24-09-19-42


#workspaceLocation: 'project'
#checkoutLocation: 'project'

tasks:
  - name: Terminal 1
    #openMode: split-left
    before: echo 'before Script'
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'
  - name: Terminal 2
    openMode: split-left
    init: npm install # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: npm run dev
  - name: Terminal 3
    openMode: split-left
    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'hello from terminal 3'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
# ports:
#   - name: Frontend
#     description: Port 3000 for the frontend
#     port: 3000
#     onOpen: open-preview
#   
#  - name: database
#     port: 5432
#     onOpen: ignore
